### ISSUE TITLE
Whitespace not removed in some situations

### ISSUE THREAD

**Issue by dotHTM** [randy3k/Whitespace#4]
While using a figlet commenting package, some permutations of # and white space prevent whitespace removal, sample file provided.
[whitespacetext.txt](https://github.com/randy3k/Whitespace/files/880261/whitespacetext.txt)

**Comment by dotHTM** [comment]
I made sure to disable all my other installed packages and restart ST 3125 before testing.

**Comment by randy3k** [comment]
Seriously, I don't understand your sample file. Are you trying to remove line 18 to 21?

![untitled](https://cloud.githubusercontent.com/assets/1690993/24474864/0a03d8f8-149c-11e7-9ae7-d66f77a94c3d.gif)

**Comment by dotHTM** [comment]
Okay, I moved my App Support/Sublime Text 3 folder to desktop, relaunched ST, enter licence, install package control, install Whitespace, install Figlet, and here's a sample file that doesn't process trailing whitespace.

![screen shot 2017-03-29 at 15 44 13](https://cloud.githubusercontent.com/assets/624132/24475761/95c29b82-1496-11e7-8dc1-a3dff1d9d075.png)

![screen shot 2017-03-29 at 15 41 58](https://cloud.githubusercontent.com/assets/624132/24475672/4e703d16-1496-11e7-8fac-5908b377d6a8.png)

[A Sample file.txt](https://github.com/randy3k/Whitespace/files/880323/A.Sample.file.txt)

**Comment by dotHTM** [comment]
removing some lines of the figlet comments allow your package to run again.

**Comment by randy3k** [comment]
Alright, it is because somehow Figlet also inserts `\f` at the end of the lines. It should be fixed now. The next version will be released to Package Control soon.

**Comment by dotHTM** [comment]
danke!

**Comment by randy3k** [comment]
Sublime Text is smart enough to remove those `\f`'s when some lines are deleted and the buffer is rerendered. It is the reason removing some lines will make it work again.

I guess you could contact Figlet's developers on this issue. I can see that those `\f`'s will break quite a number of packages.
